services:
  ros-pkg:
    build:
        context: .
        dockerfile: Dockerfile
    image: ros-pkg:latest
    container_name: ros-pkg-container
      #depends_on:
      #roscore:
      #  condition: service_healthy
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - "ROS_MASTER_URI=http://192.168.1.1:11311"
      - "ROS_IP=192.168.1.1"
      - "DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/*:/dev/*"
    command: /bin/bash

  roscore:
    image: ros:noetic-ros-core
    container_name: roscore
    healthcheck:
      test: ["CMD-SHELL", "rosversion -d"]
      interval: 3s
      timeout: 5s
      retries: 5
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - "ROS_MASTER_URI=http://192.168.1.1:11311"
      - "ROS_IP=192.168.1.1"
      - "DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/*:/dev/*"
    command: >
      bash -c "source /opt/ros/noetic/setup.bash && exec roscore"

